services:
  - type: web
    plan: free
    name: Enco-Der
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app & python -m main
    repo: https://github.com/Stanpoly/En-Co.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: AUTH_USERS 
        sync: false
      - key: Max_Tasks
        sync: false
      - key: MONGODB_URI
        sync: false
    autoDeploy: false
